apiVersion: v1
kind: Service
metadata:
  name: consalud-app-mi-perfil-service
spec:
  type: LoadBalancer
  selector:
    app: consalud-app-mi-perfil
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
